export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_REQUEST_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_REQUEST_FAILURE = 'USER_LOGIN_FAILURE'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_REQUEST_SUCCESS = 'USER_REGISTER_REQUEST_SUCCESS'
export const USER_REGISTER_REQUEST_FAILURE = 'USER_REGISTER_REQUEST_FAILURE'

export const USER_LOGOUT = 'USER_LOGOUT'